### ISSUE TITLE
Unable to run the app locally

### ISSUE THREAD

**Issue by jmichelgarcia** [mmesnjak/pet-store-4-rbc#2]
Hi there,

I'm trying to build and run locally your petstore app.
The apps builds ok (if I skip the tests).

However, when I run :
`java -jar target/*.war --spring.profiles.active=prod` I get a **connection refused error.**

What dependencies are required to run your app ? Postgresql ?

Many thanks !

**Comment by mmesnjak** [comment]
Hi Jean-Michel,

Yes for production profile a Postgresql is the database choice. Local
install on port 5432 unless configured differently in application-prod.yml

Regards,
Mišel
On Jun 22, 2016 17:04, "Jean-Michel GARCIA" notifications@github.com
wrote:

Hi there,

I'm trying to build and run locally your petstore app.
The apps builds ok (if I skip the tests).

However, when I run :
java -jar target/*.war --spring.profiles.active=prod I get a connection
refused error.

What dependencies are required to run your app ? Postgresql ?

Many thanks !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/mmesnjak/pet-store-4-rbc/issues/2, or mute the thread
https://github.com/notifications/unsubscribe/ABlp5Xa0lKYZ9aS-WfJazaqyXbzepL77ks5qOU72gaJpZM4I74io
.
